### ISSUE TITLE
DataContext

### ISSUE THREAD

**Issue by iammukeshm** [shammelburg/CoreIdentity#1]
Could you explain what datacontext is? How does it get seeded  updated to database?

I ran your solution , I was able to register/ login using the SecurityContext.
But when trying to access the Example Xontroller, It always throws exceptions.

{"Could not find stored procedure 'dbo.spInsertExample'."}

Is the SP supposed to be created on itself? TIA

**Comment by shammelburg** [comment]
> Could you explain what datacontext is? How does it get seeded  updated to database?
> 
> 
> 
> I ran your solution , I was able to register/ login using the SecurityContext.
> 
> But when trying to access the Example Xontroller, It always throws exceptions.
> 
> 
> 
> {"Could not find stored procedure 'dbo.spInsertExample'."}
> 
> 
> 
> Is the SP supposed to be created on itself? TIA 

Hi, 
The DataContext is just an example on how you would create a separate class library to access your data using SQL Server. 

It shows how you would use DI in your startup class and controller to access it. 

Thanks
