### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by shook1337** [shammelburg/CoreIdentity#6]
can u add the database? so we dont make our own one

**Comment by shammelburg** [comment]
@shook1337 You've only got to run 2 Package Manager Console commands to create the table required to run the project. This way you can configure your database how you want it.

**Comment by shook1337** [comment]
but i dont have azure for the connection string

**Comment by shook1337** [comment]
can u help me add the string because i dont have a user and password on a sql

**Comment by shammelburg** [comment]
You'll need to setup a database in Cloud (Azure) or local machine, localdb will work, or if you have Docker run SQL Server that way. Once you've set up your database, you'll have the credentials to create the connection string.

`"Server=xxx;Database=xxx;User Id=xxx;Password=xxx"` in `appsettings.Development.json`
